#!/bin/sh
name="${1%.git}"
if [ -z "$name" ]; then
    echo "Usage: delete <repo-name>"
    exit 1
fi
if [ "$name" != "$1" ]; then
    echo "Note: .git is added automatically, using \"$name\" as the repo name."
fi
if [ ! -d "/home/git/repos/$name.git" ]; then
    echo "Repo $name does not exist."
    exit 1
fi
if [ -d "/home/git/trash/$name.git" ]; then
    echo "Repo $name already exists in trash."
    exit 1
fi
if ! mv /home/git/repos/$name.git /home/git/trash/$name.git; then
    echo "Repo $name couldn't be moved to trash."
    exit 1
fi
echo "Repo $name moved to trash."
