#!/bin/sh
name="${1%.git}"
if [ -z "$name" ]; then
    echo "Usage: new <repo-name>"
    exit 1
fi
if [ "$name" != "$1" ]; then
    echo "Note: .git is added automatically, using \"$name\" as the repo name."
fi
if [ -d "/home/git/repos/$name.git" ]; then
    echo "Repo $name already exists."
    exit 1
fi
if ! git init --quiet --bare /home/git/repos/$name.git; then
    echo "Repo $name couldn't be created."
    exit 1
fi
echo "Repo created as /repos/$name.git"
