#!/bin/sh
name="${1%.git}"
if [ -z "$name" ]; then
    echo "Usage: restore-repository <repo-name>"
    exit 1
fi
if [ "$name" != "$1" ]; then
    echo "Note: .git is added automatically, using \"$name\" as the repo name."
fi
if [ ! -d "/home/git/trash/$name.git" ]; then
    echo "Repo $name is not in trash."
    exit 1
fi
if [ -d "/home/git/repos/$name.git" ]; then
    echo "Repo $name already exists in repos."
    exit 1
fi
if ! mv /home/git/trash/$name.git /home/git/repos/$name.git; then
    echo "Repo $name couldn't be restored."
    exit 1
fi
echo "Repo $name restored."
